language: python
dist: trusty
sudo: false
branches:
  except:
    - /^v\d+\.*$/
    - /^tavis-.*$/
    - /^untagged.*/
matrix:
  include:
  - python: "2.7"
    env:
    - FLAG=false
      TOXENV=py27
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
services:
- docker
install:
- travis_retry pip install tox
script:
- make test
- |
  if [[ "$FLAG" == "true" ]]; then
    set -e
    make build
    if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      pip install -U bumpversion gitchangelog pystache
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      git pull -t
      export TAG_VERSION_OLD=$(git describe --tags `git rev-list --tags --max-count=1`)
      git checkout -b travis-master-$TRAVIS_BUILD_NUMBER origin/$TRAVIS_BRANCH
      bumpversion --tag --commit --message "[skip ci] Travis Build ${TRAVIS_BUILD_NUMBER}. Update version {current_version} --> {new_version}" patch modeldb/__init__.py
      export TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
      gitchangelog > CHANGELOG.md
      git add CHANGELOG.md && git commit -m "[skip ci] Generated CHANGELOG file" CHANGELOG.md
      git tag -f $TAG_VERSION
      sed -i.bak 's/changelog\.tpl/releasenotes\.tpl/g' .gitchangelog.rc
      export ENV_RELEASE_NOTES=`gitchangelog $TAG_VERSION_OLD..HEAD`
      export RELEASE_NOTES=$(python -c "import json,os; print(json.dumps(os.environ['ENV_RELEASE_NOTES']).strip('\"'))")
    fi
  fi
after_success:
- if [[ "$FLAG" == "true" ]]; then
    bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f .coverage;
  fi
deploy:
# Publish artifacts to python repositories and create remote tag
- provider: script
  skip_cleanup: true
  script: >-
    make clean build upload &&
    git checkout master &&
    git merge travis-master-$TRAVIS_BUILD_NUMBER &&
    git push --tags https://$GITHUB_TOKEN@github.com/engapa/modeldb-basic.git $TRAVIS_BRANCH
  on:
    branch: master
    condition: $FLAG = true
# Publish on github releases
- provider: script
  skip_cleanup: true
  script: >-
    curl -X POST
      -H "Authorization: token $GITHUB_TOKEN"
      -H "Content-Type: application/json"
      -d '{"name": "$TAG_VERSION",
           "tag_name": "$TAG_VERSION",
           "target_commitish": "$TRAVIS_BRANCH"
           "body": "$RELEASE_NOTES"}'
       https://api.github.com/repos/engapa/modeldb-basic/releases
  on:
    branch: master
    condition: $FLAG = true

notifications:
  email:
    recipients:
    - engapa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always